### ISSUE TITLE
+proj=longlat not working on transformation

### ISSUE THREAD

**Issue by chathurach** [maRci002/proj4dart#14]
```
void transform() {
  final latOffset = 0.04086; // degrees
  final lonOffset = 0.36427; // degrees
  final source = Projection.get('WGS84');
  final target = Projection.parse(
      '+proj=longlat +lon_0=$lonOffset +lat_0=$latOffset +ellps=WGS84 +units=m +no_defs');
  final transform = ProjectionTuple(fromProj: source!, toProj: target);
  final transformed = transform.forward(Point(x: 7.421, y: 79.546));
  print('${transformed}');
}
```

I need to shift some coordinates to the correct location. I used the above code but it does not seems to transform the coordinates and only output the same coordinates that I give.

**Comment by maRci002** [comment]
It seems this is the expected behavior, as proj4js outputs the same results.

Paste the following script into your browser. Note that you cannot paste it into every domain, like GitHub. Instead, go to a site like https://cdnjs.com/libraries/proj4js.

```js
var script = document.createElement('script');
script.onload = function() {
    const latOffset = 0.04086; // degrees
    const lonOffset = 0.36427; // degrees
    proj4.defs('target', `+proj=longlat +lon_0=${lonOffset} +lat_0=${latOffset} +ellps=WGS84 +units=m +no_defs`);
    console.log(proj4('WGS84', 'target', [7.421, 79.546])); // Output: [7.421, 79.546]
};

var scriptPath = 'https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.10.0/proj4.js';
script.setAttribute('src', scriptPath);
document.head.appendChild(script);
```

If you disagree with the output, then create an issue in the [proj4js repository](https://github.com/proj4js/proj4js). Once the issue is fixed, just ping me here, and the fix will be underway.
