### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by arsamme** [maRci002/proj4dart#5]
@maRci002  Hi, do you have any plan to migrate? Will you accept PR if I do?

**Comment by maRci002** [comment]
I think it will be done this week. On weekdays I'm a little busy.

**Comment by arsamme** [comment]
@maRci002 Thank you.

**Comment by maRci002** [comment]
It is about 90%, I will finish tomorrow

**Comment by escamoteur** [comment]
ahh, I need this too :-) I was almost doing my own migration

**Comment by escamoteur** [comment]
Hi,

because I need this library in a null safe version I migrated it today ignoring the currently not migrated packages:

 - package:proj4dart
 - package:mgrs_dart
 - package:wkt_parser
 - package:unicode
 - package:lists

This is a migration to unsound null safety. So far I couldn't see problems, so I expect as soon as the missing packages are available that should be fine.
At some places I wasn't sure if previous nullable values should still be nullable, I left the null checks despite having changed the types to nonnullables and added a TODO comment.

I hope this is in your sense and you can use it, it was a whole day work :-)

**Comment by maRci002** [comment]
It is done. Today (Tuesday) I'm going to speak with @fegyi001 about [mgrs_dart](https://github.com/fegyi001/mgrs_dart/pull/1) / [wkt_parser](https://github.com/fegyi001/wkt-parser-dart/pull/1) pub release.

**Comment by arsamme** [comment]
@maRci002 Thank you! I hope @fegyi001 merge soon.
