### ISSUE TITLE
Accuracy issue from EPSG:26716 to EPSG:4326

### ISSUE THREAD

**Issue by deckerst** [maRci002/proj4dart#8]
I'm trying to transform from [EPSG:26716](https://epsg.io/26716) to EPSG:4326, and the results I get with proj4dart are slightly off.

Here's the code:
```dart
    final tuple = proj4.ProjectionTuple(
      fromProj: proj4.Projection.parse('+proj=utm +zone=16 +datum=NAD27 +units=m +no_defs'),
      toProj: proj4.Projection.WGS84,
    );

    final pointSrc = proj4.Point(x: 444650, y: 4640510);
    final pointForward = tuple.forward(pointSrc);
    print('Transform point ${pointSrc.toArray()} from EPSG:26716 to EPSG:4326: ${pointForward.toArray()}');
```

proj4dart gives [-87.66744437695456, 41.9143951210944]
while epsg.io gives [-87.6674992, 41.9165563]
cf https://epsg.io/transform#s_srs=26716&t_srs=4326&x=444650.0000000&y=4640510.0000000

The difference in latitude is particularly noticeable. Am I misusing the library?

**Comment by maRci002** [comment]
I'm sorry to inform you but this is the correct result since this project is based on [proj4js](https://github.com/proj4js/proj4js) which results the same.

```js
var script = document.createElement("script");
var scriptPath = "https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.8.0/proj4.js";
script.setAttribute("src", scriptPath);
document.head.appendChild(script);

script.onload = function() {
    proj4.defs('EPSG:26716', '+proj=utm +zone=16 +datum=NAD27 +units=m +no_defs');
    var result = proj4('EPSG:26716', 'WGS84').forward([444650, 4640510]);
    console.log(result);
}
```
output: `[-87.66744437695456, 41.9143951210944]`

You can run the above script in your browser's console (_note: you cannot run on every site since this is script injection and some sites like github prevents it, so go for example to http://proj4js.org/ and press F12 and paste / run the above code snippet_)

**Comment by deckerst** [comment]
Thanks for the quick response.
I thought epsg.io was a reference site giving trustworthy results, my bad.

**Comment by maRci002** [comment]
I don't know the difference between the two outputs for instance it might be only 5mm.

However for the best result [proj4js should support shift grids](https://github.com/proj4js/proj4js/issues/62) since the Earth isn't a regular sphere.
One of my job at the old company was to implement `nadgrids` support it was a hell since I had to merge the Dart (current project) and the C++ code from [OSGeo](https://github.com/OSGeo/PROJ).
This is because the worst position without shift grids were different 12 meters in Hungary.

**Comment by deckerst** [comment]
I didn't realize nad27 needed these grids. Digging further, I see that proj4js actually implemented a way to load nadgrids with https://github.com/proj4js/proj4js/pull/363 and I was now looking whether it was possible with proj4dart :)

I saw a shift ~300m South when overlaying a GeoTIFF around Chicago, and I wasn't sure if it was me, the geotiff or the projection.

**Comment by deckerst** [comment]
> If the nadgrid version is necessary

I was curious about the topic and wanted to understand what was going on, but I do not personally need this. Thanks again for taking the time to explain!

**Comment by maRci002** [comment]
#9 I just created a new issue to add nadgrids feature, when I have free time it will be added.
